/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_module_Main */

#ifndef _Included_com_module_Main
#define _Included_com_module_Main
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif6
